# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7504302f1b75daf38685462e84295aa51ae19f73038c20fd0516797356ee11447e7bea88a6a11b18f31f5340477f76b7d356194fb8fbb2738fabf3885bdbfab4

test:
  secret_key_base: 747714434d6f93eefca83430f95371234c6f5a08787c54627e388ce4b977ef4eff00981b71b7fe7be8d01b896f501929ef7d2992681b8821e353e34048a5e361

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
